### ISSUE TITLE
CSS preview

### ISSUE THREAD

**Issue by dohliam** [alexandersandberg/a11yana#4]
This is great! Very clean and readable. I've included it in this [minimal CSS collection](https://github.com/dohliam/dropin-minimal-css), which lets you preview the CSS on any page (using the included bookmarklet). I look forward to seeing how this project develops!

**Comment by alexandersandberg** [comment]
Thanks for adding the project, @dohliam. I haven't had much time to work on a11yana, but hopefully I will in the future. 🙂
